### ISSUE TITLE
pack-build-builder-push-run-list-files failed 

### ISSUE THREAD

**Issue by tppalani** [redhat-buildpacks/ubi-image-builder#16]
Hi Team,

i'm trying to configure buildpack according to readme step but what i noticed during pipelinerun pack build builder push run list files are failed with below error, when i checked 01-pipelinerun-builder.yml its has two workspace with different name of pvc.

```
message: '[User error] more than one PersistentVolumeClaim is bound'
```

```
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pack-build-builder-push-run
spec:
  #serviceAccountName: buildpacks
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/redhat-buildpacks/ubi-image-builder.git
    - name: revision
      value: main
    - name: pathInRepo
      value: /tekton/pipeline/pack-builder-image/0.1/pack-builder-image.yml

  params:
    - name: debug
      value: "true"
    - name: git-url
      value: https://github.com/redhat-buildpacks/ubi-image-builder.git
    - name: output-image
      value: "quay.io/snowdrop/ubi-builder"
    - name: packCmdBuilderFlags
      value:
      - "-v"
      - "--publish"

  workspaces:
    - name: source-dir
      persistentVolumeClaim:
        claimName: ubi-builder-vol
    - name: pack-workspace
      persistentVolumeClaim:
        claimName: pack-workspace-vol
    - name: data-store
      projected:
        sources:
          - secret:
              name: pack-config-toml
          - secret:
              name: quay-creds

```

Here is the pipeline.yaml

```
- name: list-files
      runAfter:
        - fetch-packconfig-registrysecret
      when:
        - input: $(params.debug)
          operator: in
          values: [ "true" ]
      taskSpec:
        steps:
          - name: list-source-workspace
            image: quay.io/centos/centos:latest
            script: |
              echo "List files under: $(workspaces.pack-workspace.path)"
              ls -la $(workspaces.pack-workspace.path)/
              
              ls -la $(workspaces.pack-workspace.path)/.docker/
              cat $(workspaces.pack-workspace.path)/.docker/config.json
              
              echo "List files under: $(workspaces.source-dir.path)"
              ls -la $(workspaces.source-dir.path)/
      workspaces:
        - name: pack-workspace
          workspace: pack-workspace
        - name: source-dir
          workspace: source-dir
```
